"""add auth and profiles related table

Revision ID: f4b87701b582
Revises: 
Create Date: 2026-01-30 13:18:57.651289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4b87701b582'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS auth")
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=True),
    sa.Column('is_otp_verified', sa.Boolean(), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('suspended_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['suspended_by'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_no'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_users_email'), 'users', ['email'], unique=True, schema='auth')
    op.create_index(op.f('ix_auth_users_id'), 'users', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_is_suspended'), 'users', ['is_suspended'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_users_suspended_by'), 'users', ['suspended_by'], unique=False, schema='auth')
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index('ix_auth_sessions_active', 'sessions', ['id', 'revoked', 'expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_sessions_expires_at'), 'sessions', ['expires_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_sessions_id'), 'sessions', ['id'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_sessions_revoked_at'), 'sessions', ['revoked_at'], unique=False, schema='auth')
    op.create_index(op.f('ix_auth_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='auth')
    op.create_table('profile',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('profile_picture', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=False)
    op.create_table('staff',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_staff_user_id'), 'staff', ['user_id'], unique=False)
    op.create_table('customer',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_customer_profile_id'), 'customer', ['profile_id'], unique=False)
    op.create_table('driver',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='inactive', nullable=False),
    sa.Column('status_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index(op.f('ix_driver_profile_id'), 'driver', ['profile_id'], unique=False)
    op.create_index(op.f('ix_driver_status'), 'driver', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_driver_status'), table_name='driver')
    op.drop_index(op.f('ix_driver_profile_id'), table_name='driver')
    op.drop_table('driver')
    op.drop_index(op.f('ix_customer_profile_id'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('ix_staff_user_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='sessions', schema='auth')
    op.drop_index(op.f('ix_auth_sessions_revoked_at'), table_name='sessions', schema='auth')
    op.drop_index(op.f('ix_auth_sessions_id'), table_name='sessions', schema='auth')
    op.drop_index(op.f('ix_auth_sessions_expires_at'), table_name='sessions', schema='auth')
    op.drop_index('ix_auth_sessions_active', table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_index(op.f('ix_auth_users_suspended_by'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_is_suspended'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_id'), table_name='users', schema='auth')
    op.drop_index(op.f('ix_auth_users_email'), table_name='users', schema='auth')
    op.drop_table('users', schema='auth')
    op.execute("DROP SCHEMA IF EXISTS auth")
    # ### end Alembic commands ###
